School/urls.py
from django.conf.urls import url
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'School'

urlpatterns = [
    url(r'^$', views.index_view, name='home'),
    url(r'^gallery/', views.gallery_view, name='gallery'),
    url(r'^portal/', views.portal_view, name='portal'),
    url(r'^contacts/', views.contacts_view, name='contacts'),
    url(r'^about/', views.contacts_view, name='about'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ULUMBI/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('MANAGERS.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

School/models.py
from django.db import models


class Employee(models.Model):
    empName = models.TextField()
    empPhoto = models.ImageField(upload_to='Emp Photo', blank=True)
    empDescription = models.TextField()

    def __str__(self):
        return self.empDescription + self.empName

School/views.py
from django.shortcuts import render

from .models import Employee

def index_view(request):
    writing_items = Employee.objects.all()

    context = {
        "writing_item": writing_items,
    }

    return render(request, "school/index.html", context)


def gallery_view(request):
    writing_items = Employee.objects.all()

    context = {
        "writing_item": writing_items,
    }

    return render(request, "school/gallery.html", context)


def portal_view(request):
    writing_items = Employee.objects.all()

    context = {
        "writing_item": writing_items,
    }

    return render(request, "school/portal.html", context)

def contacts_view(request):
    writing_items = Employee.objects.all()

    context = {
        "writing_item": writing_items,
    }

    return render(request, "school/contact.html", context)

def about_view(request):
    writing_items = Employee.objects.all()

    context = {
        "writing_item": writing_items,
    }

    return render(request, "school/about.html", context)

School/templates/school/about.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <title>ABOUT | ULUMBI SECONDARY SCHOOL</title>

    <script
  src="https://code.jquery.com/jquery-3.1.1.min.js"
  integrity="sha256-hVVnYaiADRTO2PzUGmuLJr8BLUSjGIZsDYGmIJLv2b8="
  crossorigin="anonymous"></script>

    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ" crossorigin="anonymous">

    <!-- jQuery library -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>

    <!-- Latest compiled JavaScript -->
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">

    <link rel="stylesheet" href="{% static 'school/style.css' %}" type="text/css">
</head>
<body class="container">
<div class="content-wrapper">
    <section class="header">
        <nav class="navbar fixed-top navbar-toggleable-md navbar-light bg-faded">
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target ="#myNav" aria-controls="myNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <a class="navbar-brand" href="index.html">Ulumbi School</a>

        <div class="collapse navbar-collapse" id="myNav">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item">
              <a class="nav-link" href="{% url 'School:home' %}">HOME<span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link active" href="{% url 'School:about' %}">ABOUT</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'School:portal' %}">PORTAL</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'School:gallery' %}">GALLERY</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'School:contact' %}">CONTACT US</a>
            </li>
          </ul>
        </div>
      </nav><!-- end of nav -->
        <div class="row" id="banner">
            <div class="col-md-12">
                <h1>About Ulumbi School</h1>
                <p></p>
            </div>
        </div>
    </section>
    <!-- the content -->
    <section>
        <h2>Brief History</h2>
        <p>Ulumbi Secondary School is a coeducational day and boarding school that was started in 1987 by the members of the local community, due to pressing need for close post-primary education. This was under the guidance of Mr. Allen Makopiyo, the then headteacher of the primary section. The strong support of the Anglican Church being critical in the inception of the school. It began striclty as a day school, but private arrangements were later made for the boarding section.</p>
            <p>The school has grown considearably in its infrastructure, population (currently 489) and staff members, standing at 13 TSC and 10 on board. This strategic plan, even aims at increasing the numbers further, as Teacher adequacy is pivotal in academic palance.</p>
            <p>This history in fact indicates clearly that due to adoption of this document, which will be our guide the school will reap a lot from further development, its lack of which, could have led to its stagnation. Over the years, the school has taken a good number of students to Universities, showing that the dream of this plan of Academic excellence, is indeed achievable and not merely, a speculation.</p>

        <h2>Core Values</h2>
        <p>As an institution, we believe in values which we instill in our students and guide us towards achieving our goals. These values are indeed significant in realizing the ambitions of the school's strategic plan. Among the values we uphold are:</p>
        <ul>
        <li><b>Discipline </b> - we view discipline as the key to scademic excellence and good life in general. The school therefore gives prominence greatly to this value. </li>
        <li><b>Academic Excellence</b> - without good academic performance, discipline clearly reflect in our student, hence we lay a lot of emphasis on this. </li>
        <li><b>Spirituality</b> - it it within our ambitions, to promote this virtue in our students even further because good performance and wisdom come with knowledge of God. </li>
        <li><b>Talent Amplification</b> - our students are talented in a variety of ares. It is also within our plan to lead them in realizing their talents and exploring them to the maximum. This will be achieved through clubs and other forums of expression. Talents added to good performance, equals excellence. </li>
        <li><b>Loyalty</b> - we also target at further modeling our students to be loyal citizens of this nation; people who will be proud to be Kenyans. </li>
        <li><b>Harmony</b> - as a school, we also impart the virtue of good/harmonious relationship among students and between the school in entirity with the neighbourhood. This harmony will be in them thereafter. </li>
        <li><b>Servicemanship</b> - The school would like to instill this virtue in the students. They would always be masters and not servants. </li>
        <li><b>Cleanliness</b> - We encourage both spiritual and physical cleanliness. This is because cleanliness in next to godliness. </li>
        <li><b>Unity in diversity</b> - Despite the different roots and cultures the students emanate from, the school aims at uniting its students and staff in general. We all share humanity and origin and should a brother/sister to one another. </li>
    </ul>

            <h2>The Administration</h2>
    </section><!-- end of content -->
    <section class="footer text-center">
        <a href="{% url 'School:contacts' %}"><span class="glyphicon glyphicon-envelope" aria-hidden="true"> </span></a>
        <ul class="ftr-nav">
            <li><a href="{% url 'School:home' %}" class="active"><span class="glyphicon glyphicon-home" aria-hidden="true"> </span></a></li>
            <li><a href="{% url 'School:about' %}">About</a></li>
            <li><a href="{% url 'School:portal' %}">Portal</a></li>
            <li><a href="{% url 'School:gallery' %}">Gallery</a></li>
        </ul>
        <div class="copy-right">
            <p>© 2017 Ulumbi Secondary School All rights reserved | <a href="/" target="_blank">  Crafted </a></p>
        </div>
    </section><!-- end of footer -->
</div>
</body>
</html>

School/templates/school/contact.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="You can reach the school through the following contact information">
    <title>CONTACT | ULUMBI SECONDARY SCHOOL</title>

    <script
  src="https://code.jquery.com/jquery-3.1.1.min.js"
  integrity="sha256-hVVnYaiADRTO2PzUGmuLJr8BLUSjGIZsDYGmIJLv2b8="
  crossorigin="anonymous"></script>

    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ" crossorigin="anonymous">

    <!-- jQuery library -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>

    <!-- Latest compiled JavaScript -->
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">

    <link rel="stylesheet" href="{% static 'school/style.css' %}" type="text/css">
</head>
<body class="container">
<div class="content-wrapper">
    <section class="header">
        <nav class="navbar fixed-top navbar-toggleable-md navbar-light bg-faded">
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target ="#myNav" aria-controls="myNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <a class="navbar-brand" href="{% url 'School:home' %}">Ulumbi School</a>

        <div class="collapse navbar-collapse" id="myNav">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item">
              <a class="nav-link" href="{% url 'School:home' %}">HOME<span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'School:about' %}">ABOUT</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'School:portal' %}">PORTAL</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'School:gallery' %}">GALLERY</a>
            </li>
            <li class="nav-item">
              <a class="nav-link active" href="{% url 'School:contacts' %}">CONTACT US</a>
            </li>
          </ul>
        </div>
      </nav><!-- end of nav -->
        <div class="row no-gutter" id="banner">
            <div class="col-sm-12">
                <h1>Contact Us</h1>
                <p>Stay close</p>
            </div>
        </div>
    </section>
    <section class="row no-gutter">
        <div class="col-sm-7">
            <h2>Send a message</h2>
            <form id="main-contact-form" name="contact-form" method="post" action="">
                <div class="form-group">
                    <input type="text" name="name" class="form-control" required="required" placeholder="Name">
                </div>
                <div class="form-group">
                    <input type="email" name="email" class="form-control" required="required" placeholder="Email Id">
                </div>
                <div class="form-group">
                    <textarea name="message" id="message" required="required" class="form-control" rows="8" placeholder="Your text here"></textarea>
                </div>
                <div class="form-group">
                    <input type="submit" name="submit" class="btn btn-submit link" value="Submit">
                </div>
            </form>
        </div>
        <div class="contact-info col-sm-5">
            <h2>Contacts</h2>
            <address>
                You can reach us through:<br>
                +254 791 583 105<br>
                +254 797 350 352

            </address>
            <h2>Visit Us</h2>
            You can also pay us a visit:
            <div id="gmap">
                <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d1995.9736649623849!2d34.55202381979797!3d0.09803712007478652!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x1780030287db4d31%3A0xd1c5605efda16c7e!2sUlumbi+Secondary+School%2C+Ulumbi%2C+Kenya!5e0!3m2!1sen!2s!4v1494431055675" width="100%" height="450" frameborder="0" style="border:0" allowfullscreen></iframe>
            </div><!-- end of map -->
        </div>
    </section><!-- end of content -->
    <div class="clearfix"></div>
    <section class="footer text-center">
        <a href="{% url 'School:contacts' %}"><span class="glyphicon glyphicon-envelope" aria-hidden="true"> </span></a>
        <ul class="ftr-nav">
            <li><a href="{% url 'School:home' %}" class="active"><span class="fa fa-home" aria-hidden="true"> </span></a></li>
            <li><a href="{% url 'School:about' %}">About</a></li>
            <li><a href="{% url 'School:portal' %}">Portal</a></li>
            <li><a href="{% url 'School:gallery' %}">Gallery</a></li>
        </ul>
        <div class="copy-right">
            <p>© 2017 Ulumbi Secondary School All rights reserved | <a href="/" target="_blank">  Crafted </a></p>
        </div>
    </section><!-- end of footer -->
</div>
</body>
</html>

School/templates/school/gallery.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <title>GALLERY | ULUMBI SECONDARY SCHOOL</title>

    <script
  src="https://code.jquery.com/jquery-3.1.1.min.js"
  integrity="sha256-hVVnYaiADRTO2PzUGmuLJr8BLUSjGIZsDYGmIJLv2b8="
  crossorigin="anonymous"></script>

    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ" crossorigin="anonymous">

    <!-- jQuery library -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>

    <!-- Latest compiled JavaScript -->
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">

    <link rel="stylesheet" href="{% static 'school/style.css' %}" type="text/css">
</head>
<body class="container">
<div class="content-wrapper">
    <section class="header">
        <nav class="navbar fixed-top navbar-toggleable-md navbar-light bg-faded">
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target ="#myNav" aria-controls="myNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <a class="navbar-brand" href="{% url 'School:home' %}">Ulumbi School</a>

        <div class="collapse navbar-collapse" id="myNav">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item">
              <a class="nav-link" href="{% url 'School:home' %}">HOME<span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'School:about' %}">ABOUT</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'School:portal' %}">PORTAL</a>
            </li>
            <li class="nav-item">
              <a class="nav-link active" href="{% url 'School:gallery' %}">GALLERY</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'School:contacts' %}">CONTACT US</a>
            </li>
          </ul>
        </div>
      </nav><!-- end of nav -->
        <div class="row" id="banner">
            <div class="col-md-12">
                <h1>Gallery</h1>
                <p>Pictures speak louder</p>
            </div>
        </div>
    </section>
    <section>
        <div class="wrapper">
                <img src="{% static 'school/images/us1.jpg' %}" class="img-responsive">
                <img src="{% static 'school/images/us4.jpg' %}" class="img-responsive">
                <img src="{% static 'school/images/us5.jpg' %}" class="img-responsive">
                <img src="{% static 'school/images/us6.jpg' %}" class="img-responsive">
                <img src="{% static 'school/images/us2.jpg' %}" class="img-responsive">
                <img src="{% static 'school/images/us3.jpg' %}" class="img-responsive">
                <img src="{% static 'school/images/us7.jpg' %}" class="img-responsive">
                <img src="{% static 'school/images/us8.jpg' %}" class="img-responsive">
                <img src="{% static 'school/images/us9.jpg' %}" class="img-responsive">
                <img src="{% static 'school/images/us10.jpg' %}" class="img-responsive">
                <img src="{% static 'school/images/us11.jpg' %}" class="img-responsive">
                <img src="{% static 'school/images/us12.jpg' %}" class="img-responsive">
                <img src="{% static 'school/images/us13.jpg' %}" class="img-responsive">
                <img src="{% static 'school/images/us14.jpg' %}" class="img-responsive">
                <img src="{% static 'school/images/us15.jpg' %}" class="img-responsive">
                <img src="{% static 'school/images/us16.jpg' %}" class="img-responsive">

        </div>
        
    </section>
    <div class="clearfix"></div>
    <section class="footer text-center">
        <a href="{% url 'School:contacts' %}"><span class="glyphicon glyphicon-envelope" aria-hidden="true"> </span></a>
        <ul class="ftr-nav">
            <li><a href="{% url 'School:home' %}" class="active"><span class="fa fa-home" aria-hidden="true"> </span></a></li>
            <li><a href="{% url 'School:about' %}">About</a></li>
            <li><a href="{% url 'School:portal' %}">Portal</a></li>
            <li><a href="{% url 'School:gallery' %}">Gallery</a></li>
        </ul>
        <div class="copy-right">
            <p>© 2017 Ulumbi Secondary School All rights reserved | <a href="/" target="_blank">  Crafted </a></p>
        </div>
        <ul class="social">
            <li><a href="#"><i class=" fa fa-facebook"></i></a></li>
            <li><a href="#"><i class=" fa fa-twitter"></i></a></li>
            <li><a href="#"><i class="fa fa-google-plus"></i></a></li>
        </ul>
    </section><!-- end of footer -->
</div>
</body>
</html>

School/templates/school/index.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Ulumbi Secondary is a mixed secondary school in Kenya...">
    <title>HOME | ULUMBI SECONDARY SCHOOL</title>

    <script
  src="https://code.jquery.com/jquery-3.1.1.min.js"
  integrity="sha256-hVVnYaiADRTO2PzUGmuLJr8BLUSjGIZsDYGmIJLv2b8="
  crossorigin="anonymous"></script>

    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ" crossorigin="anonymous">

    <!-- jQuery library -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>

    <!-- Latest compiled JavaScript -->
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">

    <link rel="stylesheet" href="{% static 'school/style.css' %}" type="text/css">
</head>
<body class="container">
<div class="content-wrapper">
    <section class="header">
        <nav class="navbar fixed-top navbar-toggleable-md navbar-light bg-faded">
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target ="#myNav" aria-controls="myNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <a class="navbar-brand" href="{% url 'School:home' %}">Ulumbi School</a>

        <div class="collapse navbar-collapse" id="myNav">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item">
              <a class="nav-link active" href="{% url 'School:home' %}">HOME<span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'School:about' %}">ABOUT</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'School:portal' %}">PORTAL</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'School:gallery' %}">GALLERY</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'School:contacts' %}">CONTACT US</a>
            </li>
          </ul>
        </div>
      </nav><!-- end of nav -->
        <div id="myCarousel" class="carousel slide" data-ride="carousel" data-interval="3000">
            <ol class="carousel-indicators">
                <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
                <li data-target="#myCarousel" data-slide-to="1"></li>
                <li data-target="#myCarousel" data-slide-to="2"></li>
            </ol>
            <div class="carousel-inner" role="listbox">
                <div class="carousel-item active">
                    <img src="{% static 'school/images/us1.jpg' %}" class="d-block img-fluid">
                </div>
                <div class="carousel-item">
                    <img src="{% static 'school/images/us2.jpg' %}" class="d-block img-fluid">
                </div>
                <div class="carousel-item">
                    <img src="{% static 'school/images/us3.jpg' %}" class="d-block img-fluid">
                </div>
            </div>

            <a class="carousel-control-prev" href="#myCarousel" role="button" data-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="sr-only">Previous</span>
            </a>
            <a class="carousel-control-next" href="#myCarousel" role="button" data-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="sr-only">Next</span>
            </a>
        </div>
      
    </section><!-- end of header -->
    <section class="content">

        <div class="clearfix"></div>

        <div id="welcome-note">
            <p>Ulumbi Secondary School is a coeducational day and boarding school that was started in 1987 by the members of the local community, due to pressing need for close post-primary education. This was under the guidance of Mr. Allen Makopiyo, the then headteacher of the primary section. The strong support of the Anglican Church being critical in the inception of the school. It began striclty as a day school, but private arrangements were later made for the boarding section. </p>
            <p>Currently under the administration of Mr Adalah S.O.M as the Principal, Mrs Dorothy Ogolla as the Deputy Principal with Eng. David Omolo as the the Chairman of the Board of Managers.</p>
            <a href="{% url 'School:about' %}"><button class="link">READ MORE</button></a>
        </div>
        <div class="clearfix"></div>

        <div class="row no-gutter text-center">
            <div class="col-12 col-sm-4 content-2" style="background-color: #1a6d22;">
                <h2 style="text-decoration: underline; text-underline-color: rgba(43,43,43,0.87);">Motto</h2>
                <p style="font-style: italic;">Aim HIgher</p>
            </div>
            <div class="col-12 col-sm-4 content-2" style="background-color: rgba(43,43,43,0.87);">
                <h2 style="text-decoration: underline;">Mission</h2>
                <p>To mould, educate and empower an all-round child through quality teaching and properly guided culture</p>
            </div>
            <div class="col-12 col-sm-4 content-2" style="background-color: #1a6d22">
                <h2 style="text-decoration: underline;">Vision</h2>
                <p>To be an excellent school in the pursuit of knowledge, skills and values.</p>
            </div>
        </div>
        <div class="clearfix"></div>

        <div class="clearfix"></div>

        <div class="row">
            <div class="col-12 col-sm-4">
                <img src="{% static 'school/images/students.png' %}" class="img-fluid">
            </div>
            <div class="col-12 col-sm-4">
                <img src="{% static 'school/images/teachers.png' %}"  class="img-fluid">
            </div>
            <div class="col-12 col-sm-4">
                <img src="{% static 'school/images/classes.png' %}" class="img-fluid">
            </div>
        </div>

        <div class="clearfix"></div>

        <div>
            <h2 class="text-center" style="text-decoration: underline;">Testimonials</h2>
            <div class="row">
                <div class="col-2">
                    <img src="{% static 'school/images/blockquote.png' %}">
                </div>
                <div class="col-10">
        <div id="testimony" class="carousel slide" data-ride="carousel" data-interval="3000">

            <div class="carousel-inner" role="listbox">
                <div class="carousel-item active">
                    <p class="testimony">My experience in this school has been nothing but exemplary <br> <span>John Doe,<br> The Council President</span> </p>
                </div>
                <div class="carousel-item">
                    <p class="testimony">My experience in this school has been nothing but amazing <br> <span>John Doe,<br> The Council President</span> </p>
                </div>
                <div class="carousel-item">
                    <p class="testimony">My experience in this school has been nothing but awesome <br> <span>John Doe,<br> The Council President</span> </p>
                </div>
            </div>
        </div>

                </div>
            </div>
        </div>
    </section>
    <section class="footer text-center">
        <a href="{% url 'School:contacts' %}"><span class="glyphicon glyphicon-envelope" aria-hidden="true"> </span></a>
        <ul class="ftr-nav">
            <li><a href="{% url 'School:home' %}" class="active"><span class="fa fa-home" aria-hidden="true"> </span></a></li>
            <li><a href="{% url 'School:about' %}">About</a></li>
            <li><a href="{% url 'School:portal' %}">Portal</a></li>
            <li><a href="{% url 'School:gallery' %}">Gallery</a></li>
        </ul>
        <div class="copy-right">
            <p>© 2017 Ulumbi Secondary School All rights reserved | <a href="/" target="_blank">  Crafted </a></p>
        </div>
    </section><!-- end of footer -->
</div>
</body>
</html>